<h2>Conseil / Audit</h2>
<p>
<strong><a href='/' rel='nofollow' title='FemtoPixel'>FemtoPixel</a></strong> est une soci&eacute;t&eacute; de conseil en technologie dont les domaines d'expertise couvrent un tr&egrave;s large panel de comp&eacute;tences : <strong>d&eacute;veloppement</strong>, <strong>gestion de projet</strong>, <strong>audit de s&eacute;curit&eacute;</strong>, <strong>assistance technique</strong> ponctuelle ou permanente.<br/>

<br/>
Nous nous appliquons notre cr&eacute;do de <strong>partenaire num&eacute;rique</strong> dans chacune de nos missions, qu'il s'agisse d'un contrat en <strong>r&eacute;gie</strong> ou en <strong>forfait</strong>, en suivant chaque projet au jour le jour.<br/>
<br/>
<strong>Experts en nouvelles technologies</strong>, nos chefs de projets sauront vous guider et vous informer, <strong>tout au long de notre collaboration</strong>, sur les comp&eacute;tences mises en jeu, l'&eacute;tat d'avancement et les d&eacute;lais.<br/>

<br/>
Quelques r&eacute;f&eacute;rences :</p>
<p>
<img src="/images/bluekey.png" alt="BlueKey Mobile" title="BlueKey Mobile" />
<br/><strong>BlueKey Mobile</strong>: Audit fonctionnel et de s&eacute;curit&eacute;, Gestion de projet Web</p>
<p>
<img src="/images/dunasys.png" alt="Dunasys" title="Dunasys" />
<br/><strong>Dunasys</strong>: Assistance à la rédaction d'un cahier des charges technique</p>