<h2>Assistance</h2>
<p>
L'informatique a beau être un outil performant, il n'est pas exempt de panne.<br/><br/>

<strong><a href='/' rel='nofollow' title='FemtoPixel'>FemtoPixel</a></strong> propose ses services pour vous accompagner à la <strong>résolution de vos problèmes</strong> en vous <strong>conseillant</strong> ou en <strong>intervenant</strong> (à distance ou à domicile) chez les <strong>particuliers</strong> ou les <strong>entreprises</strong>. <br/>
</p>
<h3>Les problèmes les plus récurrents </h3>
<ol>
  <li>Installation de "Box" Internet</li>
  <li>Attaque de virus</li>
  <li>Installation d'un programme</li>
  <li>Réinstallation d'un système</li>
</ol>
<p><span style="text-decoration: underline;">Quelques r&eacute;f&eacute;rences </span> :</p>

<p>
<img src="/images/aphp.jpg" alt="Hopital Henri Mondor" title="Hopital Henri Mondor" />
<br/><strong>Hopital Henri Mondor</strong>: Renforcement de l'équipe technique du service informatique<br/><br/></p>