<h2>D&eacute;veloppement Internet</h2>
<p>
D&eacute;velopper son activit&eacute; gr&acirc;ce &agrave; un <strong>site Web personnalis&eacute;</strong>, faire soi-m&ecirc;me ses <strong>mises &agrave; jour</strong> en quelques clics, &eacute;changer avec ses collaborateur <strong>partout dans le monde</strong> grâce à son propre <strong>Intranet</strong>, ...<br/>

Internet est aujourd'hui un atout majeur et incontournable pour votre soci&eacute;t&eacute;.<br/>
</p>
<h3>Les étapes pour réussir son site web</h3>
<ol>
  <li>&Eacute;tude</li>
  <li>Création</li>
  <li>Hébergement</li>
  <li>Référencement</li>
</ol>
<p>
Confiez vos projets &agrave; une <strong>&eacute;quipe exp&eacute;riment&eacute;e</strong> dont le travail ne s'arr&ecirc;te pas &agrave; la mise en ligne de votre site, mais qui reste votre partenaire sur le long terme !<br/>
Nous mettons d&egrave;s aujourd'hui toute notre exp&eacute;rience des technologies de l'Internet <strong>au service de votre entreprise.</strong><br/>
</p>
<p><span style="text-decoration: underline;">Quelques r&eacute;f&eacute;rences de notre &eacute;quipe Internet</span> :</p>

<p>
<img src="/images/rueavendre.gif" alt="Rue A Vendre" title="Rue A Vendre" />
<br/><strong>Rue a vendre (118712)</strong>: Développement d'un site viral (<a href="http://www.rueavendre.com/" title="Rue A Vendre" target='_blank'>www.rueavendre.com</a>)<br/><br/></p>

<p>
<img src="/images/orange.gif" alt="Orange Origami" title="Orange Origami" />
<br/><strong>Orange Origami</strong>: Développement de support technique et corrections d'API sur les révélateurs (Akinator et Forfait Origami) (<a href="http://www.orange-origami.fr/" title="Orange Origami" target='_blank'>www.orange-origami.fr</a>)<br/><br/></p>

<p>
<img src="/images/gemey-blogs.gif" alt="Gemey-Maybelline" title="Gemey-Maybelline" />
<br/><strong>Blog In The City (Gemey-Maybelline)</strong>: Mise en place d'une intégration sur un système de blog existant. (<a href="http://www.gemey-maybelline.com/Bloginthecity/" title="Blog In The City" target='_blank'>www.gemey-maybelline.com/Bloginthecity</a>)<br/><br/></p>

<p>
<img src="/images/rlagency.gif" alt="RL Agency" title="RL Agency" />
<br/><strong>RL Agency</strong>: Développement de plusieurs API de reconnaissance optiques de caracteres sur la plateforme de coliposte. <br/><br/></p>

<p>
<img src="/images/doonoyz.gif" alt="Doonoyz" title="Doonoyz" />
<br/><strong>Doonoyz</strong>: D&eacute;veloppement d'un réseau social musical, intégration d'un design, outil de streaming(<a href="http://www.doonoyz.com/" title="Doonoyz" target='_blank'>www.doonoyz.com</a>)<br/><br/></p>

<p>
<img src="/images/emploipro.gif" alt="Emploi-pro" title="Offres d'emploi. Annonces recrutement et recherche d'emploi avec Emploi-Pro" />
<br/><strong>L'usine nouvelle / Emploi-pro</strong>: D&eacute;veloppement d'un site de gestion de CV et de recherche d'emploi (<a href="http://www.emploi-pro.com/" title="Offres d'emploi. Annonces recrutement et recherche d'emploi avec Emploi-Pro" target='_blank'>www.emploi-pro.com</a>)<br/><br/></p>

<p>
<img src="/images/sephora.png" alt="LVMH / Sephora" title="LVMH / Sephora" />
<br/><strong>LVMH / Sephora</strong>: D&eacute;veloppement d'un intranet de gestion de hotline (<a href="http://www.sephora.fr/" title="Sephora La parfumerie en ligne" target='_blank'>www.sephora.fr</a>)<br/><br/></p>

<p>
<img src="/images/tac.gif" alt="La Tete Au Cube" title="La Tete Au Cube" />
<br/><strong>La Tete Au Cube</strong>: D&eacute;veloppement d'un site marchand (<a href="http://www.lateteaucube.com/" title="la t&ecirc;te au cube objets design, ou pas, gentiment d&eacute;cal&eacute;s" target='_blank'>www.lateteaucube.com</a>)<br/><br/></p>

<p>
<img src="/images/bm.gif" alt="Bordeaux Millesimes" title="Bordeaux Millesimes" />
<br/><strong>Bordeaux Millesimes</strong>: D&eacute;veloppement d'un site marchand (<a href="http://www.bordeaux-millesimes.com/" title="Bordeaux Millesimes" target='_blank'>www.bordeaux-millesimes.com</a>)<br/><br/></p>

<p>
<img src="/images/cinelive.gif" alt="CinéLive" title="CinéLive" />
<br/><strong>CinéLive</strong>: D&eacute;veloppement d'un site de présentation, d'un outil de gestion/administration de contenu et de streaming vidéo (<a href="http://www.cinelive.com/" title="CinéLive" target='_blank'>www.cinelive.com</a>) <br/>
Le site a été développé en lieu et place du CD-ROM vendu avec le magazine.<br/>
<b>UPDATE:</b> En janvier 2009, Cinélive s'arrete pour former Studio Cinélive. Le site est alors remplacé par un blog (cf. <a href='http://fr.wikipedia.org/wiki/Cin%C3%A9_Live'>http://fr.wikipedia.org/wiki/Ciné_Live</a>)
<br/></p>

<p>
<img src="/images/ccm.png" alt="Comment Ca Marche" title="Comment Ca Marche" />
<br/><strong>Comment Ca Marche</strong>: D&eacute;veloppement d'un outil de gestion/administration de vidéo en streaming (<a href="http://www.commentcamarche.net/" title="Comment Ca Marche" target='_blank'>www.commentcamarche.net</a>)<br/><br/></p>

<p>
<img src="/images/motionrights.png" alt="MotionRights" title="MotionRights" />
<br/><strong>MotionRights</strong>: D&eacute;veloppement d'un outil de protection de vid&eacute;o pour les d&eacute;tenteurs de droits (www.motionrights.com) (n'existe plus)<br/><br/></p>

<p>
<img src="/images/mooveus.jpg" alt="Mooveus" title="Mooveus" />
<br/><strong>Mooveus</strong>: D&eacute;veloppement d'une plateforme de création d'évenements et de transport mondiaux par groupe et développement d'un site de présentation (www.mooveus.com / <a href="http://pfe.gds.free.fr/" title="Mooveus" target='_blank'>http://pfe.gds.free.fr/</a>) (n'existe plus)<br/><br/></p>