<h2>Accueil</h2>

<div class='paragraph'>
Spécialiste depuis plus de 3 ans dans le développement internet, <strong><a href='/' rel='nofollow' title='FemtoPixel'>FemtoPixel</a></strong> met à disposition ses compétences pour vous accompagner à la réalisation ou à la mise à jour de votre site web, intranet...
</div>
<div class='paragraph'>
Avec l'arrivé des nouvelles technologies (Ajax, Web 2.0), votre site disposera d'une interface <strong>simple</strong> et <strong>intuitive</strong> tout en restant <strong>stable</strong>, <strong>sécurisé</strong> et <strong>robuste</strong>.
</div>
<div class='paragraph'>
<a href='mailto:contact@femtopixel.com'>Contactez nous</a> dès a présent pour établir un devis gratuit.
<ul>
  <li>Par téléphone : 09 54 26 62 84</li>
  <li>Par fax : 09 59 26 62 84</li>
  <li>Par E-mail : <a href='mailto:contact@femtopixel.com'>contact@femtopixel.com</a></li>
</ul>
</div>