<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="content-type" content="text/html"  />
		<meta name="content-language" content="fr"  />
		<meta name="revisit-after" content="3 days"  />
		<link rel="shortcut icon" href="http://www.femtopixel.com/favicon.ico" />
		<link href="/css/style.css" rel="stylesheet" type="text/css" media="screen" />
		<title>FemtoPixel&nbsp;&nbsp;|&nbsp;&nbsp;<?= $this->layout()->title ?></title>
	</head>
	<body>
		<div id="logo">
			<h1>
				<a href="/"><img src='/images/logo.gif' /></a>
			</h1>
		</div>
		<div id="menu">
			<ul>
				<li class="first"><a href="/" accesskey="1" title="Accueil">Accueil</a></li>
				<li><a href="/assist" accesskey="2" title="Assistance">Assistance</a></li>
				<li><a href="/development" accesskey="3" title="Développement Internet">Développement Internet</a></li>
				<li><a href="/advice" accesskey="4" title="Conseil / Audit">Conseil / Audit</a></li>
			</ul>
		</div>
		<hr />
		<!-- start page -->
		<div id="page">
		<!-- start content -->
			<div id="content">
				<?php echo $this->layout()->content; ?>
			</div>
			<!-- end content -->
			<div style="clear: both;">&nbsp;</div>
		</div>
		<!-- end page -->
		<div id="footer">
			<p class="credit">SIRET : 51340906000011<br/><a href='http://www.facebook.com/pages/FemtoPixel/118064237745'>Femtopixel on Facebook</a><br/>2009 <strong>FemtoPixel</strong>. All rights reserved to each owner.</p>
			<p class='legal'>contact@femtopixel.com<br/>tel : 09 54 26 62 84<br/>fax : 09 59 26 62 84</p>
		</div>
	</body>
</html>